# For debug package -- semi-incompatible build system
%define _empty_manifest_terminate_build 0
%define debug_package %{nil}

Name:		git-lfs
Version:	3.5.1
Release:	1
Group:		Development/Tools
# git-lfs doesn't like being built from tarballs (uses "git describe" and friends
# in Makefiles), so instead of grabbing
# https://github.com/git-lfs/git-lfs/archive/refs/tags/v%{version}.tar.gz
# We do
# git clone --depth 1 -b v%{version} https://github.com/git-lfs/git-lfs git-lfs-%{version}
# tar cJf git-lfs-%{version}.tar.xz git-lfs-%{version}
Source0:	git-lfs-%{version}.tar.xz
# Tarball containing go dependencies -- generated by (inside the source tree)
# running:
# export GOPATH=/tmp/.godeps
# rm -rf /tmp/.godeps
# go mod download
# cd /tmp
# tar cJf godeps-for-git-lfs-%{version}.tar.xz .godeps
Source1:	godeps-for-git-lfs-%{version}.tar.xz
# Not used by the spec and not packaged -- but useful for updating
Source1000:	package-source.sh
Summary:	Large File Storage support for git
License:	MIT
BuildRequires:	golang
BuildRequires:	ronn
BuildRequires:	make
BuildRequires:	asciidoctor
Requires:	git-core

%description
Git Large File Storage (LFS) replaces large files such as audio samples,
videos, datasets, and graphics with text pointers inside Git, while
storing the file contents on a remote server like GitHub.com

%prep
%autosetup -p1 -a 1

%build
export GOPATH="`pwd`/.godeps"
export GOPROXY="file://`pwd`/.godeps"
%make_build
%make_build man

%install
mkdir -p %{buildroot}%{_bindir} \
	%{buildroot}%{_mandir}/man1 \
	%{buildroot}%{_mandir}/man5
install -c -m 755 bin/git-lfs %{buildroot}%{_bindir}/
install -c -m 644 man/man1/*.1 %{buildroot}%{_mandir}/man1/
install -c -m 644 man/man5/*.5 %{buildroot}%{_mandir}/man5/

%files
%{_bindir}/*
%{_mandir}/man*/*
